### ISSUE TITLE
Demo converting to json giving wrong Tickrates

### ISSUE THREAD

**Issue by mariosemes** [markus-wa/cs-demo-minifier#31]
Hi there,

Used the tool few times to generate my own VDM files and found out that the tickrates arent synced with the actual demo tickrates.
https://i.imgur.com/0kNQt5f.png

Example on the image.
Left, player DIED tickrate exported with csminify.
Right, actual demo tickrate when the player DIED.

Any ideas how to dig deeper and find out whats happening?

**Comment by markus-wa** [comment]
Hi @mariosemes , can you please upload the demo and send me the link?

cheers!

**Comment by LarsKoelpin** [comment]
Could it be, that parser.CurrentFrame() is something else that parser.GameState.IngameTick()?

I guess this could relate to the issue, as I ran into a similar issue (Ticks were offset) on a project of mine. 
I fixed it by using GameState.IngameTick instead, which behaved as I expected.

Maybe this could be the issue here (csgominify#142)

**Comment by markus-wa** [comment]
The two funcs are different, correct 🙂

| // CurrentFrame return the number of the current frame, aka. 'demo-tick' (Since demos often have a different tick-rate than the game).

Note that, generally speaking, frame = demo and tick = game.
Demos can for instance be recorded at 32 frames per seconds while the game was played on 128 ticks per second.

**Comment by markus-wa** [comment]
I think this could be due to corrupt headers but it's hard to tell without repro. If so a switch to `TickRate()` and `IngameTick()` could indeed solve the issue

**Comment by markus-wa** [comment]
might be fixed by #45

**Comment by markus-wa** [comment]
should be fixed by v0.4.3: https://github.com/markus-wa/cs-demo-minifier/releases/tag/v0.4.3

**Comment by markus-wa** [comment]
@LarsKoelpin if you are interested to implement the fix in your project: https://github.com/markus-wa/cs-demo-minifier/pull/45/files :slightly_smiling_face:
